// Generated by https://quicktype.io
import 'package:json_annotation/json_annotation.dart';

part 'producto.g.dart';

@JsonSerializable()
class Producto {

  String id;
  num precio;
  String nombre;
  String descripcion;
  String location;
  String img;

  Producto({
    this.id,
    this.precio,
    this.nombre,
    this.descripcion,
    this.location,
    this.img
  });
  factory Producto.fromJson(Map<String, dynamic> json) =>
      _$ProductoFromJson(json);
  Map<String, dynamic> toJson() => _$ProductoToJson(this);
}

class Productos {
  List<Producto> items = new List();

  Productos();

  Productos.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    for (var item in jsonList) {
      final result = new Producto.fromJson(item);
      items.add(result);
    }
  }
}