// Generated by https://quicktype.io
import 'package:json_annotation/json_annotation.dart';

part 'venta.g.dart';

@JsonSerializable()
class Venta {

  String id;
  num precio;
  String nombre;
  String img;

  Venta({
    this.id,
    this.precio,
    this.nombre,
    this.img
  });
  factory Venta.fromJson(Map<String, dynamic> json) =>
      _$VentaFromJson(json);
  Map<String, dynamic> toJson() => _$VentaToJson(this);
}

class Ventas {
  List<Venta> items = new List();

  Ventas();

  Ventas.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    for (var item in jsonList) {
      final result = new Venta.fromJson(item);
      items.add(result);
    }
  }
}